baseURL = "https://github.com/adrienraffy-beep/hugo.github.io"
languageCode = "fr-fr"
title = "Mon Canard Blog"
theme = "minimal-pc"

[params]
  description = "Critiques acerbes et analyses techniques."
